version: '3'

services:
  db-inventory:
    container_name: db-inventory
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_inventory
      POSTGRES_USER: taliani
      POSTGRES_PASSWORD: 151200
    ports:
      - 5431:5432
    expose:
      - 5431

  db-orders:
    container_name: db-orders
    image: mysql:8.0.35
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms_orders
      MYSQL_USER: taliani
      MYSQL_PASSWORD: 151200
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    expose:
      - 3307

  db-products:
    container_name: db-products
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_products
      POSTGRES_USER: taliani
      POSTGRES_PASSWORD: 151200
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432

  db-keycloak:
    container_name: db-keycloak
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_keycloak
      POSTGRES_USER: taliani
      POSTGRES_PASSWORD: 151200
    ports:
      - 5433:5433
    expose:
      - 5433
    command: -p 5433

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.1
    command: ["start-dev"]
    ports:
      - 8181:8181
    expose:
      - 8181
    depends_on:
      - db-keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db-keycloak
      DB_DATABASE: db_keycloak
      DB_PORT: 5433
      DB_USER: taliani
      DB_PASSWORD: 151200
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8181

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.4.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.4.3
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
