insert into public.product (sku, name, description, price, status) values ('SWL-912', 'Hammer', 'hac habitasse platea dictumst etiam faucibus cursus urna ut', 5.07, true);
insert into public.product (sku, name, description, price, status) values ('RYB-098', 'Screwdriver', 'vel accumsan tellus nisi eu orci', 3.47, false);
insert into public.product (sku, name, description, price, status) values ('XOP-379', 'Drill', 'velit id pretium iaculis diam erat fermentum justo nec', 12.66, true);
insert into public.product (sku, name, description, price, status) values ('YPL-440', 'Wrench', 'ipsum primis in faucibus orci luctus et ultrices', 6.23, true);
insert into public.product (sku, name, description, price, status) values ('SAK-021', 'Pliers', 'lobortis vel dapibus at diam nam tristique tortor', 9.49, false);
insert into public.product (sku, name, description, price, status) values ('NKT-903', 'Nails', 'ultrices erat tortor sollicitudin mi sit amet', 0.57, false);
insert into public.product (sku, name, description, price, status) values ('RUK-811', 'Saw', 'viverra dapibus nulla suscipit ligula in lacus curabitur', 8.12, true);
insert into public.product (sku, name, description, price, status) values ('ABW-133', 'Paintbrush', 'vel ipsum praesent blandit lacinia erat', 2.34, false);
insert into public.product (sku, name, description, price, status) values ('CSQ-224', 'Tape Measure', 'ligula suspendisse ornare consequat lectus in est risus auctor', 1.63, true);
insert into public.product (sku, name, description, price, status) values ('GDH-493', 'Level', 'ut mauris eget massa tempor convallis nulla neque libero convallis', 8.41, false);
